# Generated by Django 6.0.5 on 2026-05-12 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=100, unique=True)),
                ('family', models.CharField(max_length=100)),
                ('commercial_name', models.CharField(max_length=255)),
                ('density', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('glass_fill', models.FloatField(default=0)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='rfq_drawings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('material_text', models.TextField(blank=True, null=True)),
                ('estimated_volume', models.FloatField(blank=True, null=True)),
                ('estimated_weight', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('detected_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RFQ.material')),
            ],
        ),
        migrations.CreateModel(
            name='PartComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_part_number', models.CharField(max_length=100)),
                ('estimated_weight', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='RFQ.drawinganalysis')),
            ],
        ),
    ]
