# Generated by Django 6.0.5 on 2026-05-14 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ', '0002_material_material_type_material_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingDetectedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_material_text', models.TextField(blank=True, null=True)),
                ('detected_family', models.CharField(blank=True, max_length=100, null=True)),
                ('detected_color', models.CharField(blank=True, max_length=50, null=True)),
                ('detected_pigment', models.CharField(blank=True, max_length=100, null=True)),
                ('detected_supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('glass_fill', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0)),
                ('text_position', models.IntegerField(blank=True, null=True)),
                ('bom_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='alternate_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='base_resin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_reinforced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='manufacturer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='pigment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='reinforcement_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_code', 'family', 'supplier'], name='RFQ_materia_materia_2d7874_idx'),
        ),
        migrations.AddField(
            model_name='drawingdetectedmaterial',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_materials', to='RFQ.drawinganalysis'),
        ),
        migrations.AddField(
            model_name='drawingdetectedmaterial',
            name='detected_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RFQ.material'),
        ),
    ]
