# Generated by Django 6.0.5 on 2026-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ', '0003_drawingdetectedmaterial_material_alternate_names_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='RFQ_materia_materia_2d7874_idx',
        ),
        migrations.AddField(
            model_name='drawinganalysis',
            name='gemini_raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingdetectedmaterial',
            name='component_volumen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingdetectedmaterial',
            name='component_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_code'], name='RFQ_materia_materia_fa33e9_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['commercial_name'], name='RFQ_materia_commerc_4cca31_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['family'], name='RFQ_materia_family_ffaa51_idx'),
        ),
    ]
