# Generated by Django 6.0.5 on 2026-06-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ', '0004_remove_material_rfq_materia_materia_2d7874_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='last_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Last price'),
        ),
        migrations.AddField(
            model_name='material',
            name='last_purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last modification date'),
        ),
    ]
